export {
  dealKeys,
  useDeals,
  useConfirmedDealsTotal,
  useDealDetail,
  useDealLogs,
  useUploadDDU,
  useUploadPaymentProof,
  useUpdateDealComment,
  useSubmitForReview,
  useAdminApproveDeal,
  useAdminRejectDeal,
  useDeveloperConfirmDeal,
  useDeveloperRejectDeal,
} from "./model/queries";
